name: Kobold
description: A system to get google sheet data, and show to a user.
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  provider: ^5.0.0
  data_table_2: ^2.0.3
  liquid_progress_indicator: ^0.4.0
  slide_digital_clock: ^1.0.2
  easy_splash_screen:
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/Icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/Icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "path/to/Icon.png"

flutter:
  fonts:
    - family: KenyanCoffee
      fonts:
        - asset: fonts/kenyanCoffeeRG.ttf
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/